name: Hugo Build and Deploy to S3

on:
  push:
    branches: [main]

env:
  obj-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  obj-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  region: "us-east-1"
  bucket: "static-missingmila"

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master

      - name: Deploy Hugo to Object Storage
        uses: AlbertMorenoDEV/deploy-hugo-to-s3-action@v0.0.5
        with:
          hugo-version: 0.92.0
          aws-access-key-id: ${{ env.obj-access-key }}
          aws-secret-access-key: ${{ env.obj-secret-key }}
          target: "production"

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.1
        with:
          provider: linode # default is linode
          access_key: ${{ env.obj-access-key }}
          secret_key: ${{ env.obj-secret-key }}

      - name: Update File Permissions
        run: |
          s3cmd setacl s3://${{ env.bucket }} --acl-public --recursive
