name: Build and Deploy Missing Mila to Linode Object Storage

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    uses: Coto-Studio/workflows/.github/workflows/hugo-build-and-deploy.yml@main
    secrets:
      obj-access-key: ${{ secrets.LINODE_ACCESS_KEY }}
      obj-secret-key: ${{ secrets.LINODE_SECRET_KEY }}
