name: Hugo Build and Deploy to S3

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master

      - name: Deploy Hugo to Object Storage
        uses: AlbertMorenoDEV/deploy-hugo-to-s3-action@v0.0.5
        with:
          hugo-version: 0.92.0
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.1
        with:
          provider: linode # default is linode
          region: "us-east-1"
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Update File Permissions
        run: |
          s3cmd setacl s3://static-missingmila/ --acl-public --recursive
